// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestPocBackend.Data;

#nullable disable

namespace QuestPocBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528020504_InitialCreateWithSeed")]
    partial class InitialCreateWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestPocBackend.Data.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PatientId = "PT-8842",
                            Status = "Completed",
                            TestName = "Comprehensive Metabolic Panel"
                        },
                        new
                        {
                            Id = 2,
                            PatientId = "PT-1094",
                            Status = "In Progress",
                            TestName = "Lipid Panel with Reflex"
                        },
                        new
                        {
                            Id = 3,
                            PatientId = "PT-3321",
                            Status = "Pending",
                            TestName = "Hemoglobin A1c"
                        },
                        new
                        {
                            Id = 4,
                            PatientId = "PT-5541",
                            Status = "Completed",
                            TestName = "Vitamin D, 25-Hydroxy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
